subroutine init_solvent_polarization

  use quadrature ,only: Rotxx, Rotxy, Rotxz, Rotyx, Rotyy, Rotyz, Rotzx, Rotzy, Rotzz, angGrid, molRotGrid
  use input      ,only: input_log

  implicit none

  ! Compute the charge density of a single solvant molecule in Fourier-space, and electrostatic potential generated by a such distribution
  if( input_log('polarization',.true.).eqv..true.) then
    call chargeDensityAndMolecularPolarizationOfASolventMoleculeAtOrigin (Rotxx,Rotxy,Rotxz,Rotyx,Rotyy,Rotyz,Rotzx,Rotzy,Rotzz)
  end if

end subroutine init_solvent_polarization
